services:
  web:
    build: .
    command: bundle exec rails server -b 0.0.0.0
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
